---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
implicit:
- сайт должен быть доступен на русском и на английском языках
- при добавлении товара в корзину должно всплывать уведомление " Товар успешно добавлен в корзину"
- при оформлении заказа должно появляться уведомление с текстом " Ваш заказ успешно оформлен"
- при переключении языков сайта должны переводиться автоматически названия товаров и краткие описания товаров
- пользователь должен иметь возможность заказать товар и просматривать сделанные заказы
